### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by lk108** [DavidSM100/crypto-whisper#1]
Hi, I'm the author of a messenger that implements Webxdc and I would like to discuss about the use of the method randomUUID() of the crypto API, and possibly provide a PR with a fallback. However, I couldn't find license information. Would you be willing to define a license under which the app is published?

**Comment by davidsm10** [comment]
Hello, I added a license.

**Comment by davidsm10** [comment]
I also updated the project, so you should sync before doing anything.
If you have any questions you can contact me over email:
d.s.m.011010@gmail.com
